/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EntityIdList: typeof import('./src/components/EntityIdList.vue')['default']
    ResolverResponseView: typeof import('./src/components/ResolverResponseView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopFilterBar: typeof import('./src/components/TopFilterBar.vue')['default']
  }
}
