<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>se.swedenconnect.oidf</groupId>
        <artifactId>openid-federation-parent</artifactId>
        <version>0.5.6</version>
    </parent>
    <artifactId>oidf-tooling-parent</artifactId>
    <version>${service-revision}</version>
    <packaging>pom</packaging>

    <name>Sweden Connect :: OpenID Federation :: Tooling :: Parent POM</name>
    <description>Parent POM for Sweden Connect OpenID Federation Tooling</description>
    <url>https://www.swedenconnect.se</url>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <connection>scm:git:https://github.com/swedenconnect/openid-federation-tooling.git</connection>
        <developerConnection>scm:git:https://github.com/swedenconnect/openid-federation-tooling.git</developerConnection>
        <url>https://github.com/swedenconnect/openid-federation-tooling/</url>
    </scm>

    <organization>
        <name>Sweden Connect</name>
        <url>https://www.swedenconnect.se</url>
    </organization>

    <repositories>
        <repository>
            <id>github</id>
            <name>Github Swedenconnect Common</name>
            <url>https://maven.pkg.github.com/swedenconnect/*</url>
        </repository>
    </repositories>
    <modules>
        <module>backend</module>
    </modules>
    <distributionManagement>
        <snapshotRepository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
        <repository>
            <id>ossrh</id>
            <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </distributionManagement>
    <developers>

        <developer>
            <name>Per Fredrik Plars</name>
            <email>pf@litsec.se</email>
            <organization>PA Partner</organization>
            <organizationUrl>https://www.digg.se</organizationUrl>
        </developer>

    </developers>

    <properties>
        <!-- Project properties -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <service-revision>0.0.1-SNAPSHOT</service-revision>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.1.0</version>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>