openid:
  federation:
    tooling:
      trustAnchorEntityId: "https://fed.sandbox.swedenconnect.se/trustanchor"
      discoveryUri: "https://fed.sandbox.swedenconnect.se/trustanchor/discovery"
      resolverUri: "https://fed.sandbox.swedenconnect.se/trustanchor/resolve"


