name: Snapshot publication of docker image
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main

jobs:
  publish-docker:
    uses: swedenconnect/openid-federation-commons/.github/workflows/docker-ghcr-publish.yml@v0.5.10
    secrets: inherit
    with:
      service-path: backend
      frontend-path: frontend
