name: Versioned publication of docker image
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/docker-ghcr-publish.yml@v0.5.10
    secrets: inherit
    with:
      service-path: backend
      frontend-path: frontend
      revision-property: service-revision
  finalize-release:
    uses: swedenconnect/openid-federation-commons/.github/workflows/finalize.yml@v0.5.10
    secrets: inherit
    with:
      auto-update-revision: false
      revision-property: service-revision
    needs: release