name: Automated review steps
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  review:
    uses: swedenconnect/openid-federation-commons/.github/workflows/reusable-review.yml@v0.5.10
    secrets: inherit